allowBuilds:
  '@parcel/watcher': true
  msgpackr-extract: true
minimumReleaseAgeExclude:
  - '@effuse/cli@1.0.3'
  - '@effuse/compiler@1.0.5'
  - '@effuse/core@2.0.3'
  - '@effuse/i18n@1.1.3'
  - '@effuse/ink@1.2.3'
  - '@effuse/query@2.0.3'
  - '@effuse/router@1.2.3'
  - '@effuse/server@1.0.3'
  - '@effuse/store@1.1.3'
  - '@effuse/use@1.2.3'
